apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-integration
  labels:
    app: dev-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-integration
  template:
    metadata:
      labels:
        app: dev-integration
    spec:
      containers:
        - name: dev-integration
          image: dev-integration:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: shared-config

            - configMapRef:
                name: dev-integration-config

            - secretRef:
                name: shared-secrets