apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-email-server
  labels:
    app: dev-email-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-email-server
  template:
    metadata:
      labels:
        app: dev-email-server
    spec:
      containers:
        - name: dev-email-server
          image: dev-email-server:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: shared-config

            - configMapRef:
                name: dev-email-server-config

            - secretRef:
                name: shared-secrets