apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-sandbox
  labels:
    app: dev-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-sandbox
  template:
    metadata:
      labels:
        app: dev-sandbox
    spec:
      containers:
        - name: dev-sandbox
          image: dev-sandbox:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            # ------------ PostgreSQL --------------
            - name: DATABASE_URL
              value: "jdbc:postgresql://postgres-service:5432/dev_sandbox"

            - name: POSTGRES_USER
              value: "postgres"

            - name: POSTGRES_PASSWORD
              value: "root"

            # ------------ RabbitMQ ----------------
            - name: RABBIT_HOST
              value: "rabbitmq-service"

            - name: RABBIT_MANAGEMENT_BASE_URL
              value: "http://rabbitmq-service:15672/api"

            # ------------ Redis (if needed) -------
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""

            # ------------ Elasticsearch -----------
            - name: ELASTIC_HOST
              value: "elasticsearch-service"
            - name: ELASTIC_PORT
              value: "9200"
            - name: ELASTIC_SCHEME
              value: "http"
            - name: ELASTIC_USERNAME
              value: "admin"
            - name: ELASTIC_PASSWORD
              value: "admin"
