apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-sandbox
  labels:
    app: dev-sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-sandbox
  template:
    metadata:
      labels:
        app: dev-sandbox
    spec:
      containers:
        - name: dev-sandbox
          image: dev-sandbox:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: shared-config

            - configMapRef:
                name: dev-sandbox-config

            - secretRef:
                name: shared-secrets